### ISSUE TITLE
`PairSession` type declaration incomplete

### ISSUE THREAD

**Issue by robertklep** [athombv/node-homey-apps-sdk-v3-types#8]
The type declaration file for [`PairSession`](https://github.com/athombv/node-homey-apps-sdk-v3-types/blob/production/lib/PairSession.d.ts) only declares a single method `setHandler`. The other methods, [mentioned here](https://apps-sdk-v3.developer.homey.app/PairSession.html), are missing.

**Comment by jeroenwienk** [comment]
Fixed in 0.3.3.
